### ISSUE TITLE
The game is not recording the results correctly on the main page

### ISSUE THREAD

**Issue by daveag77** [ppissanetzky/fortee2#13]
First case:
When the game tables are announced, the partner name is missing and the opponents names are wrong.  See first issue attachment

Second case:
When results are over, the game correctly reports the winner and in the box below says "better luck next time".  There should be congrats to the winners and the losers get the comment above.

Also noted here is the forfeits on the first round.  The F is beside the wrong team on the top box but is correct on the bottom box,

![First Issue](https://github.com/ppissanetzky/fortee2/assets/133181707/5387f8b0-98bd-493d-93da-0234561a070e)
![Second Issue](https://github.com/ppissanetzky/fortee2/assets/133181707/e053e51a-c10a-49c6-bf1e-0899036ee4be)

**Comment by ppissanetzky** [comment]
The forfeits look to be in the right place.

**Comment by ppissanetzky** [comment]
Fixed
