### ISSUE TITLE
Issue with Creating Recurring Tournaments

### ISSUE THREAD

**Issue by daveag77** [ppissanetzky/fortee2#23]
Pablo, this is a high priority one.  Red is not able to set up recurring tournaments.  Single ones, yes.  Recurring, no.  She is going to set up a 24x7, 4 tournaments/hr schedule so that folks will have tournaments available around the clock and not show up to find no games going and an hour wait for a tournament.

Once this one is done we will use the email list to start contacting everyone with instructions on how to get to the new site, register, and play.  I want there to be tournaments before we do that mailout though.

Please prioritize this one!

**Comment by ppissanetzky** [comment]
This is fixed in 5.12.0
